apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom
  namespace: monitoring
spec:
  project: default
  source:
    chart: prometheus-community
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 59.1.0
    helm:
      values: |


  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring