apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom
  namespace: default

spec: 
  project: default

source: 
  repoURL: github.com/realexcel2021/app-of-apps
  path: umbrella-chart
  targetRevision: HEAD
  helm:
    valuesFiles:
      - values.yaml

destination:
  namespace: monitoring
  server: https://kubernetes.default.svc