apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/realexcel2021/app-of-apps
    path: umbrella-chart
    targetRevision: HEAD
    helm:
      valueFiles: 
        - values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring